const form=document.getElementById('proxyForm');const input=document.getElementById('urlInput');const viewer=document.getElementById('viewer');const status=document.getElementById('status');const blankButton=document.getElementById('blankButton');const backButton=document.getElementById('backButton');const forwardButton=document.getElementById('forwardButton');const reloadButton=document.getElementById('reloadButton');
const historyStack=[];let historyIndex=-1;
function normalizeUrl(value){let v=value.trim();if(!v)throw new Error('Enter a URL.');if(!/^[a-z][a-z0-9+.-]*:\/\//i.test(v))v='https://'+v;const u=new URL(v);if(!['http:','https:'].includes(u.protocol))throw new Error('Only HTTP and HTTPS URLs are supported.');return u.href}
function proxyUrl(target){return `${location.origin}/proxy?url=${encodeURIComponent(target)}`}
function setStatus(message,type=''){status.textContent=message;status.className=`status ${type}`.trim()}
function load(target,add=true){try{const url=normalizeUrl(target);input.value=url;viewer.src=proxyUrl(url);if(add){historyStack.splice(historyIndex+1);historyStack.push(url);historyIndex=historyStack.length-1}setStatus(`Loading ${url}`,'ok')}catch(e){setStatus(e.message,'error')}}
form.addEventListener('submit',e=>{e.preventDefault();load(input.value)});
blankButton.addEventListener('click',()=>{try{const url=normalizeUrl(input.value);const win=window.open('about:blank','_blank');if(!win){setStatus('Allow pop-ups for this site to open about:blank.','error');return}const src=proxyUrl(url);win.document.write(`<!doctype html><html><head><title>Web Viewer</title><style>html,body,iframe{margin:0;width:100%;height:100%;border:0}body{overflow:hidden}</style></head><body><iframe src="${src.replaceAll('"','&quot;')}" allowfullscreen></iframe></body></html>`);win.document.close();setStatus('Opened in a new about:blank window.','ok')}catch(e){setStatus(e.message,'error')}});
backButton.addEventListener('click',()=>{if(historyIndex>0){historyIndex--;load(historyStack[historyIndex],false)}});forwardButton.addEventListener('click',()=>{if(historyIndex<historyStack.length-1){historyIndex++;load(historyStack[historyIndex],false)}});reloadButton.addEventListener('click',()=>{if(viewer.src){const current=viewer.src;viewer.src='';requestAnimationFrame(()=>viewer.src=current)}});
